# Generated by Django 5.0.4 on 2024-04-19 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_delete_dim_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DIM_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_nascimento_USUARIO', models.DateField(null=True, verbose_name='Data de nascimento do usuario')),
                ('Idade_USUARIO', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade do usuario')),
                ('Curso_USUARIO', models.CharField(choices=[('design_grafico', 'Design Gráfico'), ('ciencia_computacao', 'Ciência da Computação')], default='', max_length=50, verbose_name='Curso do usuario')),
                ('Unidade_USUARIO', models.CharField(choices=[('unidade_independencia', 'Unidade Independência'), ('unidade_central', 'Unidade Central'), ('unidade_direito', 'Unidade Direito')], default='', max_length=30, verbose_name='Unidade de ensino')),
                ('Cidade_usuario', models.CharField(default='', max_length=100, verbose_name='Cidade do usuario')),
                ('Telefone_usuario', models.CharField(default='', max_length=20, unique=True, verbose_name='Telefone do usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
