# Generated by Django 5.0.4 on 2024-04-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dim_usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='dim_usuario',
            name='Email_usuario',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='E-mail do usuario'),
        ),
        migrations.AddField(
            model_name='dim_usuario',
            name='Nome_USUARIO',
            field=models.CharField(default='', max_length=150, verbose_name='Nome do usuario'),
        ),
        migrations.AddField(
            model_name='dim_usuario',
            name='Senha_usuario',
            field=models.CharField(default='', max_length=50, verbose_name='Senha do usuario'),
        ),
    ]
