# Generated by Django 5.0.4 on 2024-04-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_dim_usuario_user_dim_usuario_email_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dim_usuario',
            old_name='Cidade_usuario',
            new_name='Cidade_USUARIO',
        ),
        migrations.RenameField(
            model_name='dim_usuario',
            old_name='Email_usuario',
            new_name='Email_USUARIO',
        ),
        migrations.RenameField(
            model_name='dim_usuario',
            old_name='Senha_usuario',
            new_name='Senha_USUARIO',
        ),
        migrations.RenameField(
            model_name='dim_usuario',
            old_name='Telefone_usuario',
            new_name='Telefone_USUARIO',
        ),
    ]
