# Generated by Django 5.0.4 on 2024-04-20 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_cidade_usuario_dim_usuario_cidade_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dim_usuario',
            options={'verbose_name': 'Usuario_aplicação', 'verbose_name_plural': 'Usuarios_aplicação'},
        ),
    ]
