# Generated by Django 5.0.4 on 2024-04-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_dim_usuario_curso_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dim_usuario',
            name='Online_USUARIO',
            field=models.BooleanField(default=False),
        ),
    ]
