# Generated by Django 5.0.4 on 2024-04-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_sessao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_usuario',
            name='Email_USUARIO',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail do usuario'),
        ),
    ]
