# Generated by Django 5.0.4 on 2024-05-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_dim_usuario_curso_usuario_and_more'),
        ('usuarios', '0012_alter_dim_usuario_email_usuario'),
    ]

    operations = [
    ]
