# Generated by Django 5.0.4 on 2024-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_merge_20240529_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dim_usuario',
            name='Online_USUARIO',
        ),
        migrations.AlterField(
            model_name='dim_usuario',
            name='Email_USUARIO',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-mail do usuario'),
        ),
        migrations.DeleteModel(
            name='sessao_usuario',
        ),
    ]
