# Generated by Django 5.0.4 on 2024-04-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0003_remove_dim_usuario_estado_remove_dim_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dim_produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
