# Generated by Django 5.0.4 on 2024-04-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0005_alter_fat_venda_id_usuario_delete_dim_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fat_venda',
            name='Id_USUARIO',
        ),
    ]
