# Generated by Django 5.0.4 on 2024-04-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0006_remove_fat_venda_id_usuario'),
        ('usuarios', '0004_remove_dim_usuario_user_dim_usuario_email_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat_venda',
            name='Id_USUARIO',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.dim_usuario'),
        ),
    ]
