# Generated by Django 5.0.4 on 2024-04-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0008_fat_pedido_compra_id_adm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fat_pedido_compra',
            options={'verbose_name': 'Pedido de Compra', 'verbose_name_plural': 'Pedidos de Compra'},
        ),
    ]
