# Generated by Django 5.0.4 on 2024-04-27 20:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0010_alter_fat_pedido_compra_id_adm'),
        ('usuarios', '0010_alter_dim_usuario_email_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAT_Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_total_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total da venda')),
                ('Data_VENDA', models.DateField(default=django.utils.timezone.now, verbose_name='Data da venda')),
            ],
        ),
        migrations.AddField(
            model_name='dim_produto',
            name='Customizacao_PRODUTO',
            field=models.CharField(choices=[('tamanho', 'Tamanho'), ('nome_estampa', 'Nome na Estampa'), ('rede_social', 'Arroba rede social')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dim_produto',
            name='Nome_PRODUTO',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Nome do produto'),
        ),
        migrations.CreateModel(
            name='FAT_item_nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qtd_item', models.IntegerField(default=1, verbose_name='Quantidade de venda')),
                ('Valor_total_item', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor total por produto')),
                ('Personalizacao_1', models.CharField(blank=True, max_length=30, null=True)),
                ('Personalizacao_2', models.CharField(blank=True, max_length=30, null=True)),
                ('Personalizacao_3', models.CharField(blank=True, max_length=30, null=True)),
                ('Id_FORNECEDOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_vendas.dim_fornecedor')),
                ('Id_PRODUTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_vendas.dim_produto')),
                ('Id_USUARIO', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.dim_usuario')),
                ('Nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_vendas.fat_nota')),
            ],
        ),
        migrations.DeleteModel(
            name='FAT_venda',
        ),
    ]
