# Generated by Django 5.0.4 on 2024-04-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0011_fat_nota_dim_produto_customizacao_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dim_produto',
            name='Customizacao_PRODUTO',
        ),
    ]
