# Generated by Django 5.0.4 on 2024-04-28 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0014_alter_fat_item_nota_id_fornecedor'),
        ('usuarios', '0010_alter_dim_usuario_email_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fat_item_nota',
            name='Id_PRODUTO',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_vendas.dim_produto'),
        ),
        migrations.AlterField(
            model_name='fat_item_nota',
            name='Id_USUARIO',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.dim_usuario'),
        ),
    ]
