# Generated by Django 5.0.4 on 2024-04-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0015_alter_fat_item_nota_id_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fat_item_nota',
            name='Nota_fiscal',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_vendas.fat_nota'),
        ),
    ]
