# Generated by Django 5.0.4 on 2024-04-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0016_alter_fat_item_nota_nota_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fat_item_nota',
            name='Id_FORNECEDOR',
        ),
    ]
