# Generated by Django 5.0.4 on 2024-04-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0018_alter_fat_item_nota_id_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fat_item_nota',
            options={'verbose_name': 'ItemPedido', 'verbose_name_plural': 'ItemPedidos'},
        ),
        migrations.AddField(
            model_name='dim_produto',
            name='ID_FORNECEDOR',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='site_vendas.dim_fornecedor'),
        ),
    ]
