# Generated by Django 5.0.4 on 2024-04-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0019_alter_fat_item_nota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dim_fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='fat_nota',
            options={'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterField(
            model_name='dim_produto',
            name='Preco_venda_PRODUTO',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True, verbose_name='Preço de venda do produto'),
        ),
    ]
