# Generated by Django 5.0.4 on 2024-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_vendas', '0020_alter_dim_fornecedor_options_alter_fat_nota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat_nota',
            name='Encerrada',
            field=models.BooleanField(default=False),
        ),
    ]
